# Site settings
title: Starving Artist Jekyll Theme
email: ctarwater@chrisanthropic.com
author: Chrisanthropic

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: Witty description here.

# Only use this if you are serving your site via Github Pages
github:
  url: "https://chrisanthropic.github.io"

header: yes
header_sm: images/logo.png
header_med: images/logo.png
header_large: images/logo.png
header_xl: images/logo.png

# Formspree contact Form
contact_form: "https://formspree.io/ctarwater@chrisanthropic.com"


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site


# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: images/posts/
      destination: /images/posts/thumbs
      resize: "150x150^"
      gravity: "center"
      extent: "150x150"

#Autogenerate smaller size for small screens       
    small:
      source: images/posts/
      destination: /images/posts/small
      resize: "350"

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
