# Site settings
title: Starving Artist Jekyll Theme
email: ctarwater@chrisanthropic.com
author: Chrisanthropic

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: Witty description here.

# Only use this if you are serving your site via Github Pages
github:
  url: "https://chrisanthropic.github.io/starving-artist-jekyll-theme"

header: logo.png


# Formspree contact Form
contact_form: "https://formspree.io/ctarwater@chrisanthropic.com"


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
gems:
  - jekyll-feed
  - jekyll-assets

feed:
  path: atom.xml

  

## Jekyll-assets
assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/images/posts
    - _assets/fonts
  cache: .asset-cache
  autoprefixer:
    browsers:
      - "last 2 versions"
    
## End of Jekyll-Assets

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: _site/assets/posts/
      destination: /_site/assets/thumbs
      resize: "150x150^"
      gravity: "center"
      extent: "150x150"

#### SEO Stuff
# Google Analytics
google_universal_analytics:           #enter your Google Analytics ID
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image: author.jpg            #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image: author.jpg             #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
