# Site settings
name: Starving Artist Jekyll Theme
email: 
author: Chrisanthropic

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: > # this means to ignore newlines until "baseurl:"
  Witty description here.

baseurl: /starving-artist-jekyll-theme
#url: https://chrisanthropic.github.io
url: /

header: yes
header_sm: images/logo.png
header_med: images/logo.png
header_large: images/logo.png
header_xl: images/logo.png


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
